# Generated by Django 4.2.3 on 2026-04-15 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('is_system', 'name'),
            },
        ),
        migrations.CreateModel(
            name='WorkerStatusSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('online', 'Online'), ('degraded', 'Degraded'), ('offline', 'Offline')], default='online', max_length=16)),
                ('active_jobs_count', models.PositiveIntegerField(default=0)),
                ('queued_jobs_count', models.PositiveIntegerField(default=0)),
                ('failed_jobs_count', models.PositiveIntegerField(default=0)),
                ('heartbeat_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at', 'worker_name'),
                'indexes': [models.Index(fields=['worker_name', 'created_at'], name='ops_workers_worker__3c0e68_idx'), models.Index(fields=['status', 'heartbeat_at'], name='ops_workers_status_12ec24_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=160)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_internal_operator', models.BooleanField(default=True)),
                ('allowed_workspace', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('force_password_reset', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='ops.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__username',),
            },
        ),
        migrations.CreateModel(
            name='SystemHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('django_app', 'Django App'), ('database', 'Database'), ('nmap_binary', 'Nmap Binary'), ('queue_service', 'Queue Service'), ('scheduler', 'Scheduler'), ('storage', 'Storage')], max_length=64)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('error', 'Error'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('summary', models.TextField(blank=True, default='')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-checked_at', '-id'),
                'indexes': [models.Index(fields=['service_name', 'checked_at'], name='ops_systemh_service_b9f79c_idx'), models.Index(fields=['status', 'checked_at'], name='ops_systemh_status_0802cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='PermissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_key', models.CharField(choices=[('manage_users', 'Manage Users'), ('manage_settings', 'Manage Settings'), ('manage_profiles', 'Manage Profiles'), ('manage_schedules', 'Manage Schedules'), ('view_system_health', 'View System Health'), ('run_scans', 'Run Scans'), ('archive_results', 'Archive Results'), ('generate_reports', 'Generate Reports')], max_length=64)),
                ('is_allowed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_rules', to='ops.role')),
            ],
            options={
                'ordering': ('role__name', 'permission_key'),
            },
        ),
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True)),
                ('value_text', models.TextField(blank=True, default='')),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('category', models.CharField(choices=[('general', 'General'), ('scan_policy', 'Scan Policy'), ('allowed_targets', 'Allowed Targets'), ('notifications', 'Notifications'), ('exports', 'Exports'), ('ui', 'Theme & UI')], max_length=32)),
                ('label', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_app_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('category', 'key'),
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('target_type', models.CharField(max_length=120)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('summary', models.TextField()),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='permissionrule',
            constraint=models.UniqueConstraint(fields=('role', 'permission_key'), name='uniq_role_permission_rule'),
        ),
        migrations.AddIndex(
            model_name='appsetting',
            index=models.Index(fields=['category', 'is_active'], name='ops_appsett_categor_683105_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['action', 'created_at'], name='ops_adminau_action_6ef982_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['target_type', 'target_id'], name='ops_adminau_target__dafd2b_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['actor', 'created_at'], name='ops_adminau_actor_i_ac81b6_idx'),
        ),
    ]
