# Generated by Django 4.2.3 on 2026-04-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionrule',
            name='permission_key',
            field=models.CharField(choices=[('view_dashboard', 'View Dashboard'), ('view_targets', 'View Targets'), ('manage_targets', 'Manage Targets'), ('view_scans', 'View Running Scans'), ('create_scan_request', 'Create Scan Requests'), ('control_scan_executions', 'Control Scan Executions'), ('view_results', 'View Scan Results'), ('compare_results', 'Compare Results'), ('view_history', 'View Scan History'), ('manage_history', 'Manage Scan History'), ('view_reports', 'View Reports'), ('generate_reports', 'Generate Reports'), ('manage_reports', 'Manage Reports'), ('view_schedules', 'View Schedules'), ('manage_schedules', 'Manage Schedules'), ('view_notifications', 'View Notifications'), ('view_assets', 'View Assets'), ('manage_assets', 'Manage Assets'), ('manage_settings', 'Manage Settings'), ('manage_users', 'Manage Users'), ('manage_roles', 'Manage Roles'), ('manage_profiles', 'Manage Scan Profiles'), ('view_system_health', 'View System Health')], max_length=64),
        ),
    ]
