# Generated by Django 4.2.3 on 2026-04-15 06:11

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('is_administrator', models.BooleanField(default=False, verbose_name='Is Administrator')),
                ('is_operator', models.BooleanField(default=False, verbose_name='Is Operator')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'tbl_user',
            },
        ),
        migrations.CreateModel(
            name='UserLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_snapshot', models.CharField(blank=True, db_index=True, default='', max_length=150, verbose_name='Username')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='Description')),
                ('ip_address', models.CharField(blank=True, default='', max_length=45, verbose_name='IP Address')),
                ('request_method', models.CharField(blank=True, default='', max_length=10, verbose_name='Request Method')),
                ('path', models.CharField(blank=True, default='', max_length=500, verbose_name='Path')),
                ('device', models.CharField(blank=True, default='', max_length=255, verbose_name='Device')),
                ('operating_system', models.CharField(blank=True, default='', max_length=255, verbose_name='Operating System')),
                ('browser', models.CharField(blank=True, default='', max_length=255, verbose_name='Browser')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('action_type', models.CharField(blank=True, choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Failed Login'), ('admin_create', 'Admin Create'), ('admin_update', 'Admin Update'), ('admin_delete', 'Admin Delete')], db_index=True, default='', max_length=32, verbose_name='Action Type')),
                ('target_model', models.CharField(blank=True, default='', max_length=120, verbose_name='Target Model')),
                ('target_object_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Target Object ID')),
                ('object_repr', models.CharField(blank=True, default='', max_length=255, verbose_name='Object')),
                ('is_success', models.BooleanField(default=True, verbose_name='Successful')),
                ('action_datetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Action Datetime')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Logs',
                'verbose_name_plural': 'User Logs',
                'db_table': 'db_user_logs',
                'ordering': ('-action_datetime', '-id'),
            },
        ),
    ]
