# Generated by Django 4.2.3 on 2026-04-15 12:32

import apps.accounts.models.user_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.models.user_models.UserManager()),
            ],
        ),
    ]
