# Generated by Django 4.2.3 on 2026-04-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogs',
            name='location',
            field=models.CharField(blank=True, default='Unknown', max_length=160, verbose_name='Location'),
        ),
    ]
