# Generated by Django 4.2.3 on 2026-04-15 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0003_scanexecution_scanresult_scanportresult_scaneventlog_and_more'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('canonical_identifier', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('operating_system', models.CharField(blank=True, max_length=255)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('risk_level', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='info', max_length=16)),
                ('owner_name', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('monitoring', 'Monitoring'), ('archived', 'Archived')], default='monitoring', max_length=16)),
                ('current_open_ports_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='targets.target')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='AssetSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=255)),
                ('open_ports_json', models.JSONField(blank=True, default=list)),
                ('services_json', models.JSONField(blank=True, default=list)),
                ('raw_summary_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='assets.asset')),
                ('source_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_snapshots', to='scans.scanresult')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AssetChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('ports_added', 'Ports Added'), ('ports_removed', 'Ports Removed'), ('service_changed', 'Service Changed'), ('os_changed', 'OS Changed'), ('asset_created', 'Asset Created'), ('asset_updated', 'Asset Updated')], max_length=32)),
                ('summary', models.TextField()),
                ('diff_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='assets.asset')),
                ('current_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_change_logs', to='assets.assetsnapshot')),
                ('previous_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_change_logs', to='assets.assetsnapshot')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='assetsnapshot',
            index=models.Index(fields=['asset', 'created_at'], name='assets_asse_asset_i_a664a5_idx'),
        ),
        migrations.AddIndex(
            model_name='assetchangelog',
            index=models.Index(fields=['asset', 'change_type', 'created_at'], name='assets_asse_asset_i_27415a_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['risk_level', 'status'], name='assets_asse_risk_le_eec624_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['last_scanned_at'], name='assets_asse_last_sc_f5f9ee_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['canonical_identifier'], name='assets_asse_canonic_4560f8_idx'),
        ),
    ]
