# Generated by Django 4.2.3 on 2026-04-15 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('targets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('scan_type', models.CharField(choices=[('host_discovery', 'Host Discovery'), ('quick_tcp', 'Quick TCP'), ('top_100', 'Top 100'), ('top_1000', 'Top 1000'), ('service_detection', 'Service Detection'), ('safe_basic', 'Safe Basic')], default='safe_basic', max_length=32)),
                ('port_scope', models.CharField(blank=True, default='', max_length=128)),
                ('enable_host_discovery', models.BooleanField(default=True)),
                ('enable_service_detection', models.BooleanField(default=True)),
                ('enable_version_detection', models.BooleanField(default=False)),
                ('enable_os_detection', models.BooleanField(default=False)),
                ('enable_traceroute', models.BooleanField(default=False)),
                ('enable_dns_resolution', models.BooleanField(default=True)),
                ('timing_profile', models.CharField(choices=[('normal', 'Normal'), ('balanced', 'Balanced'), ('fast', 'Fast')], default='normal', max_length=16)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scan_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('is_system', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ScanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('host_discovery', 'Host Discovery'), ('quick_tcp', 'Quick TCP'), ('top_100', 'Top 100'), ('top_1000', 'Top 1000'), ('service_detection', 'Service Detection'), ('safe_basic', 'Safe Basic')], default='safe_basic', max_length=32)),
                ('port_input', models.CharField(blank=True, default='', max_length=255)),
                ('enable_host_discovery', models.BooleanField(default=True)),
                ('enable_service_detection', models.BooleanField(default=True)),
                ('enable_version_detection', models.BooleanField(default=False)),
                ('enable_os_detection', models.BooleanField(default=False)),
                ('enable_traceroute', models.BooleanField(default=False)),
                ('enable_dns_resolution', models.BooleanField(default=True)),
                ('timing_profile', models.CharField(choices=[('normal', 'Normal'), ('balanced', 'Balanced'), ('fast', 'Fast')], default='normal', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('validated', 'Validated'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('validation_summary', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_requests', to='scans.scanprofile')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_scans', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_requests', to='targets.target')),
            ],
            options={
                'ordering': ('-requested_at',),
                'indexes': [models.Index(fields=['status', 'requested_at'], name='scans_scanr_status_987e3f_idx'), models.Index(fields=['scan_type'], name='scans_scanr_scan_ty_472369_idx')],
            },
        ),
    ]
