# Generated by Django 4.2.3 on 2026-04-15 12:53

import apps.scans.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_seed_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_id', models.CharField(default=apps.scans.models.generate_execution_id, editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('queue_status', models.CharField(choices=[('waiting', 'Waiting'), ('assigned', 'Assigned'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='waiting', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('worker_name', models.CharField(blank=True, max_length=120)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('current_stage', models.CharField(blank=True, max_length=120)),
                ('status_message', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('priority', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='scans.scanrequest')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_snapshot', models.CharField(max_length=255)),
                ('host_status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('partial', 'Partial'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('total_open_ports', models.PositiveIntegerField(default=0)),
                ('total_closed_ports', models.PositiveIntegerField(default=0)),
                ('total_filtered_ports', models.PositiveIntegerField(default=0)),
                ('total_services_detected', models.PositiveIntegerField(default=0)),
                ('os_guess', models.CharField(blank=True, max_length=255)),
                ('raw_output_text', models.TextField(blank=True)),
                ('raw_output_xml', models.TextField(blank=True)),
                ('parsed_output_json', models.JSONField(blank=True, default=dict)),
                ('traceroute_data_json', models.JSONField(blank=True, default=list)),
                ('script_output_json', models.JSONField(blank=True, default=dict)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='scans.scanexecution')),
            ],
            options={
                'ordering': ('-generated_at',),
            },
        ),
        migrations.CreateModel(
            name='ScanPortResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.PositiveIntegerField()),
                ('protocol', models.CharField(default='tcp', max_length=16)),
                ('state', models.CharField(default='open', max_length=32)),
                ('service_name', models.CharField(blank=True, max_length=120)),
                ('service_version', models.CharField(blank=True, max_length=255)),
                ('risk_level', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='info', max_length=16)),
                ('extra_data_json', models.JSONField(blank=True, default=dict)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_results', to='scans.scanresult')),
            ],
            options={
                'ordering': ('port', 'protocol'),
            },
        ),
        migrations.CreateModel(
            name='ScanEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='scans.scanexecution')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['host_status', 'generated_at'], name='scans_scanr_host_st_096c22_idx'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['target_snapshot'], name='scans_scanr_target__04b6a5_idx'),
        ),
        migrations.AddIndex(
            model_name='scanportresult',
            index=models.Index(fields=['risk_level', 'port'], name='scans_scanp_risk_le_e61c48_idx'),
        ),
        migrations.AddConstraint(
            model_name='scanportresult',
            constraint=models.UniqueConstraint(fields=('result', 'port', 'protocol'), name='uniq_scan_port_result_per_protocol'),
        ),
        migrations.AddIndex(
            model_name='scanexecution',
            index=models.Index(fields=['status', 'queue_status', 'created_at'], name='scans_scane_status_71eaf3_idx'),
        ),
        migrations.AddIndex(
            model_name='scanexecution',
            index=models.Index(fields=['is_archived', 'created_at'], name='scans_scane_is_arch_1c8cac_idx'),
        ),
        migrations.AddIndex(
            model_name='scaneventlog',
            index=models.Index(fields=['event_type', 'created_at'], name='scans_scane_event_t_654d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='scaneventlog',
            index=models.Index(fields=['execution', 'created_at'], name='scans_scane_executi_51374c_idx'),
        ),
    ]
