# Generated by Django 4.2.3 on 2026-04-15 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0003_scanexecution_scanresult_scanportresult_scaneventlog_and_more'),
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('executive_summary', 'Executive Summary'), ('technical_report', 'Technical Report'), ('comparison_report', 'Comparison Report'), ('per_host_report', 'Per-Host Report')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('is_system', 'name'),
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('report_type', models.CharField(choices=[('executive_summary', 'Executive Summary'), ('technical_report', 'Technical Report'), ('comparison_report', 'Comparison Report'), ('per_host_report', 'Per-Host Report')], max_length=32)),
                ('format', models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('json', 'JSON'), ('txt', 'TXT')], default='html', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('failed', 'Failed'), ('archived', 'Archived')], default='generated', max_length=16)),
                ('summary', models.TextField(blank=True)),
                ('report_payload_json', models.JSONField(blank=True, default=dict)),
                ('rendered_html', models.TextField(blank=True)),
                ('generated_file_path', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='assets.asset')),
                ('comparison_left_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_as_comparison_left', to='scans.scanresult')),
                ('comparison_right_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_as_comparison_right', to='scans.scanresult')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('report_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='reports.reporttemplate')),
                ('source_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_from_execution', to='scans.scanexecution')),
                ('source_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_from_result', to='scans.scanresult')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['report_type', 'status', 'created_at'], name='reports_gen_report__03c5ee_idx'), models.Index(fields=['format', 'created_at'], name='reports_gen_format_a21813_idx')],
            },
        ),
    ]
