# Generated by Django 4.2.3 on 2026-04-15 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0003_scanexecution_scanresult_scanportresult_scaneventlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('scan_type', models.CharField(choices=[('host_discovery', 'Host Discovery'), ('quick_tcp', 'Quick TCP'), ('top_100', 'Top 100'), ('top_1000', 'Top 1000'), ('service_detection', 'Service Detection'), ('safe_basic', 'Safe Basic')], default='safe_basic', max_length=32)),
                ('port_input', models.CharField(blank=True, default='', max_length=255)),
                ('enable_host_discovery', models.BooleanField(default=True)),
                ('enable_service_detection', models.BooleanField(default=True)),
                ('enable_version_detection', models.BooleanField(default=False)),
                ('enable_os_detection', models.BooleanField(default=False)),
                ('enable_traceroute', models.BooleanField(default=False)),
                ('enable_dns_resolution', models.BooleanField(default=True)),
                ('timing_profile', models.CharField(choices=[('normal', 'Normal'), ('balanced', 'Balanced'), ('fast', 'Fast')], default='normal', max_length=16)),
                ('schedule_type', models.CharField(choices=[('one_time', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='daily', max_length=16)),
                ('recurrence_rule', models.CharField(blank=True, max_length=255)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scan_schedules', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_schedules', to='scans.scanprofile')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_schedules', to='targets.target')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ScheduleRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('triggered', 'Triggered'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_run_logs', to='scans.scanexecution')),
                ('generated_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_run_logs', to='reports.generatedreport')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_logs', to='schedules.scanschedule')),
            ],
            options={
                'ordering': ('-run_at',),
                'indexes': [models.Index(fields=['status', 'run_at'], name='schedules_s_status_02b201_idx'), models.Index(fields=['schedule', 'run_at'], name='schedules_s_schedul_497557_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='scanschedule',
            index=models.Index(fields=['is_enabled', 'next_run_at'], name='schedules_s_is_enab_470e74_idx'),
        ),
        migrations.AddIndex(
            model_name='scanschedule',
            index=models.Index(fields=['schedule_type', 'created_at'], name='schedules_s_schedul_d42605_idx'),
        ),
    ]
