# Generated by Django 4.2.3 on 2026-04-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanschedule',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
